{% set version = "2.0.12" %}

package:
  name: emscripten
  version: {{ version }}

source:
  url: https://github.com/emscripten-core/emscripten/archive/{{ version }}.tar.gz
  sha256: ed8fa2c610bfbfb97c509bd95bffdc92c9eedc62808de8963ccddf9c07a7a0de
  patches:
    - remove_revision_file_setting.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # node modules need to compile native extensions
  host:
    - python
    - binaryen
    - nodejs
  run:
    - python
    - binaryen
    - nodejs
    - lld
    - clang
    - clangxx
    - llvm-tools
    # for google closure compiler
    - zlib

test:
  commands:
    - emcc --help
    - emcc $RECIPE_DIR/testfile.c
    - node a.out.js

about:
  home: https://emscripten.org/
  license: MIT OR NCAS
  license_file: LICENSE
  summary: Emscripten compiles C and C++ to WebAssembly using LLVM and Binaryen. Emscripten output can run on the Web, in Node.js, and in wasm runtimes.
  dev_url: https://github.com/emscripten-core/emscripten

extra:
  recipe-maintainers:
    - wolfv
