{% set version = "3.1.9" %}

package:
  name: emscripten
  version: '{{ version }}'

source:
  url: https://github.com/emscripten-core/emscripten/archive/{{ version }}.tar.gz
  sha256: b07bf8328eac2ac59957dac27fc8e91f5ac4d3f39354710b798f7e552c33d430
  patches:
    - remove_revision_file_setting.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # node modules need to compile native extensions
  host:
    - python
    - binaryen
    - nodejs
    - lld
    - clang
    - clangxx
    - llvm-tools
  run:
    - python
    - {{ pin_compatible("binaryen", max_pin="x") }}
    - nodejs
    - lld
    - clang
    - clangxx
    - llvm-tools
    # for google closure compiler
    - zlib

test:
  commands:
    - emcc --help
    - emcc $RECIPE_DIR/testfile.c
    - node a.out.js

about:
  home: https://emscripten.org/
  license: MIT OR NCAS
  license_file: LICENSE
  summary: Emscripten compiles C and C++ to WebAssembly using LLVM and Binaryen. Emscripten output can run on the Web, in Node.js, and in wasm runtimes.
  dev_url: https://github.com/emscripten-core/emscripten

extra:
  recipe-maintainers:
    - wolfv
